# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_dD16zvkJr2H3S9-1BEkaiooa6gtYKe
"""

import numpy as np
from numpy import random
import math
import matplotlib.pyplot as plt

random.seed(1)

N = 10000

hit = 0


pi_value = []
circle_area = []


plt.figure(figsize=(6,6))
# Square
plt.plot([0,0,5,5,0], [0,5,5,0,0], c='blue')
# Arc
interval = 3/N
ax = []
ay = []
for i in range(1, N+1):
    x = i*interval
    ax.append(x)
    y = np.sqrt(9-x*x)
    ay.append(y)

plt.plot(ax, ay, c='blue')

hx = []
hy = []

mx = []
my = []

for i in range(1, N+1):
    x = random.uniform(0,5)
    y = random.uniform(0,5)
    
    if y <= np.sqrt(9-x*x):
        hit += 1
        hx.append(x)
        hy.append(y)

    else:
        mx.append(x)
        my.append(y)

    if(i in [100,1000,10000]):
        pi_value.append((hit*4*25)/(i*9))

est_pi = (hit*4*25)/(N*9)

for i in pi_value: 
  circle_area.append(4*i*3*3)
        
        
plt.scatter(hx, hy, c='red',s=5)
plt.scatter(mx, my, c='blue',s=5)

print('value of PI:', est_pi)
print('Area of circle:', circle_area)
print(pi_value)

x_bar = ['100', '1000', '10000']
xpos = np.arange(len(x_bar))

plt.bar(xpos,pi_value, label="Pi value")

plt.xticks(xpos, x_bar)
plt.ylabel("Estimated PI Value")
plt.xlabel("N(Number Of Trials)")

plt.legend()

x_bar = ['100', '1000', '10000']
xpos = np.arange(len(x_bar))

plt.bar(xpos,circle_area, label="Area")

plt.xticks(xpos, x_bar)
plt.ylabel("Estimated Area Value")
plt.xlabel("N(Number Of Trials)")

plt.legend()