# -*- coding: utf-8 -*-
"""problem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyrzHMqzoh3CWVjTSs6SRIrksSp4NqCH
"""

import numpy as np
from numpy import random
import math
import matplotlib.pyplot as plt

random.seed(1)


N = 10000
hit = 0

pi_value = []
area = []

plt.figure(figsize=(6,6))
# Square
plt.plot([0,4,4,0,0], [0,0,2,2,0], c='blue')
# Arc
plt.plot([0,4,3,1,0], [0,0,1,1,0], c='blue')
interval = 1/1000
ax = []
ay = []
for i in range(-1000, 1001):
    x = i*interval+2
    ax.append(x)
    y = math.sqrt(1-(x-2)*(x-2))+1
    ay.append(y)

plt.plot(ax, ay, c='blue')


hx = []
hy = []

mx = []
my = []

for i in range(1, N+1):
    x = random.uniform(0,4)
    y = random.uniform(0,2)
    
   
    if x >= 1 and x <= 3 and y <= np.sqrt(1-(x-2)*(x-2))+1:
        hit += 1
        hx.append(x)
        hy.append(y)
    elif x < 1 and y <=x :
        hit += 1
        hx.append(x)
        hy.append(y)
    elif x > 3 and y <=-x + 4:
        hit += 1
        hx.append(x)
        hy.append(y)
    else:
        mx.append(x)
        my.append(y)
    if(i in [100,1000,10000]):
        pi_value.append((hit*4*25)/(N*9))
        print("Needles : ", i )
        plt.scatter(hx, hy, c='red',s=5)
        plt.scatter(mx, my, c='blue',s=5)