# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uiG1EVZWvPHci8YeyZLak6QvlotauHr3
"""

import math
import matplotlib.pyplot as plt

# SHOOTS
Ashoot=0
Bshoot=0
Cshoot=0
Dshoot=0

# speed of cars (m/min)
SA   = 3 
SB   = 5 
SC   = 7 
SD   = 2 

# initial position of cars
XA = [10]
YA = [0]
XB = [0]
YB = [10]
XC = [10]
YC = [10]
XD = [0]
YD = [0]

for t in range(0,20):
  disBD = math.sqrt((XD[t]-XB[t])**2 + (YD[t]-YB[t])**2)
  disDA = math.sqrt((XA[t]-XD[t])**2 + (YA[t]-YD[t])**2)
  disAC = math.sqrt((XC[t]-XA[t])**2 + (YC[t]-YA[t])**2)
  disCB = math.sqrt((XB[t]-XC[t])**2 + (YB[t]-YC[t])**2)
  # print(dis)
    
  # Destroy condition check
  if (disBD < 5):
    print("D <-- A on {}-th minute!!! Target at: ({},{}) & Pursuer at: ({},{})".format(t,XB[t],YB[t],XD[t],YD[t]))
    Dshoot = Dshoot+ 1

  if (disDA < 5):
    print("A <-- D on {}-th minute!!! Target at: ({},{}) & Pursuer at: ({},{})".format(t,XD[t],YD[t],XA[t],YA[t]))
    Ashoot = Ashoot+ 1
    
  if (disAC < 5):
    print("C <-- A on {}-th minute!!! Target at: ({},{}) & Pursuer at: ({},{})".format(t,XA[t],YA[t],XC[t],YC[t]))
    Cshoot = Cshoot+ 1

  if (disCB < 5):
    print("B <-- C on {}-th minute!!! Target at: ({},{}) & Pursuer at: ({},{})".format(t,XC[t],YC[t],XB[t],YB[t]))
    Bshoot = Bshoot+ 1

            

# Movement of A 
  Acos_thet = (XC[t]-XA[t])/disAC
  Asin_thet = (YC[t]-YA[t])/disAC

  #new coordinates  
  new_A_x = XA[t] + SA*Acos_thet
  new_A_y = YA[t] + SA*Asin_thet
    
  XA.append(new_A_x)
  YA.append(new_A_y)

# Movement of B 
  Bcos_thet = (XD[t]-XB[t])/disBD
  Bsin_thet = (YD[t]-YB[t])/disBD

  #new coordinates  
  new_B_x = XB[t] + SB*Bcos_thet
  new_B_y = YB[t] + SB*Bsin_thet
    
  XB.append(new_B_x)
  YB.append(new_B_y)

# Movement of C 
  Ccos_thet = (XB[t]-XC[t])/disCB
  Csin_thet = (YB[t]-YC[t])/disCB

  #new coordinates  
  new_C_x = XC[t] + SC*Ccos_thet
  new_C_y = YC[t] + SC*Csin_thet
    
  XC.append(new_C_x)
  YC.append(new_C_y)


# Movement of D 
  Dcos_thet = (XA[t]-XD[t])/disDA
  Dsin_thet = (YA[t]-YD[t])/disDA

  #new coordinates  
  new_D_x = XD[t] + SD*Dcos_thet
  new_D_y = YD[t] + SD*Dsin_thet
    
  XD.append(new_D_x)
  YD.append(new_D_y)

  print("On {}-th minute".format(t),"cordinets of {A,B,C,D} : {","(",XA[t],",",YA[t],")","(",XB[t],",",YB[t],")","(",XC[t],",",YC[t],")","(",XD[t],",",YD[t],")}")

print("A got shot {}- times, B got shot {}- times, C got shot {}- times, D got shot {}- times,".format(Ashoot,Bshoot,Cshoot,Dshoot))

print("Coordinates of A:")
print(XA, YA, sep='\n')
print("Coordinates of B:")
print(XB, YB, sep='\n')
print("Coordinates of C:")
print(XC, YC, sep='\n')
print("Coordinates of D:")
print(XD, YD, sep='\n')

plt.figure(figsize=(10,10))
plt.plot(XA,YA,marker='o',label='A')
plt.plot(XB,YB,marker='o',label='B')
plt.plot(XC,YC,marker='o',label='C')
plt.plot(XD,YD,marker='o',label='D')
plt.legend()
plt.show()