# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJKSDlgx3xWKhR-Fy1XvWbOxMeUcgQTq
"""

import matplotlib.pyplot as plt
import math


Z1 =[12,7] 
m1 = 16
Z2 =[3,5]
m2 = 17
Z3 =[2,7]
m3 = 15

U=[]

for i in range(2,5000):
  Z1_temp = (13*Z1[i-1]+Z1[i-2]+3)%m1
  Z1.append(Z1_temp)
  u1=Z1_temp/m1

  Z2_temp = (12*(Z2[i-1]**2)+13*Z2[i-2])%m2
  Z2.append(Z2_temp)
  u2=Z2_temp/m2

  Z3_temp = (Z3[i-1]**3+Z3[i-2])%m3
  Z3.append(Z3_temp)
  u3=Z3_temp/m3

  ures = (ui1+u2+u3)

  if(ures<1):
    U.append(ures)
  else:
    whole = math.floor(ures)    
    frac = ures - whole
    U.append(frac)

#print(U)

plt.hist(U[:100],bins=20)
plt.show

plt.hist(U[:1000],bins=20)
plt.show

plt.hist(U,bins=20)
plt.show